{% set name = "castxml" %}
{% set version = "0.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/CastXML/CastXML/archive/v{{ version }}.tar.gz
  sha256: 7a2e5ae99c66b5b44e682f261248cd874fdd7554f4a24fc31d09ac5b6dcde7e5

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
  host:
    - clangdev
    - libclang
    - llvmdev
    - zlib
    - libclang-cpp
  run:
    - libclang-cpp

# Test is executed in the build to avoid requiring ninja as a run dependency

about:
  home: https://github.com/CastXML/CastXML
  summary: 'CastXML is a C-family abstract syntax tree XML output tool.'
  description: |
    CastXML is a C-family abstract syntax tree XML output tool.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  # The doc_url and dev_url are optional.
  doc_url: https://github.com/CastXML/CastXML/blob/master/doc/manual/castxml.1.rst
  dev_url: https://github.com/CastXML/CastXML

extra:
  recipe-maintainers:
    - wbthomason
    - zkingston
